language: cpp

# AMD: little-endian
# s390x: big-endian
matrix:
  archi:
  - amd64
#  - s390x

  include:
  - os: linux
    dist: bionic
    compiler: gcc
    env:
      - COMPILER=g++-5
      - GCOV=gcov-5
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: [g++-5]
  - os: linux
    dist: bionic
    compiler: gcc
    env:
      - COMPILER=g++-6
      - GCOV=gcov-6
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: [g++-6]
  - os: linux
    dist: bionic
    compiler: gcc
    env:
      - COMPILER=g++-7
      - GCOV=gcov-7
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: [g++-7]
  - os: linux
    dist: bionic
    compiler: gcc
    env:
      - COMPILER=g++-8
      - GCOV=gcov-8
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: [g++-8]
  - os: linux
    dist: bionic
    compiler: gcc
    env:
      - COMPILER=g++-9
      - GCOV=gcov-9
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: [g++-9]
  - os: linux
    dist: bionic
    env:
      - COMPILER=clang++-7
      - GCOV=gcov-7
    addons:
      apt:
        sources: *sources
        packages: clang-7
  - os: osx
    env:
      - COMPILER=clang++
      - GCOV=gcov

branches:
  only:
    - master

before_install:
 - cd "${TRAVIS_BUILD_DIR}"
 - set SUDO=sudo
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./.integration/travis-install-linux.sh ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./.integration/travis-install-osx.sh ; fi

script:
 - ./.integration/travis-run-tests.sh

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]]; then ./.integration/travis-deploy.sh" ; fi
