//=====================================================================
// MyLogger: A basic logger.
// Copyright 2018 Quentin Quadrat <lecrapouille@gmail.com>
//
// This file is part of MyLogger.
//
// MyLogger is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with MyLogger.  If not, see <http://www.gnu.org/licenses/>.
//=====================================================================

#include "Core/DataPath.hpp"
#include <algorithm>
#include <cstdlib>
#include <sstream>
#include <sys/stat.h>

// Include project_info.hpp to get the data path baked in at build time. This
// file is generated by MyMakefile.
#include "project_info.hpp"

#if defined(__APPLE__)
#  include <climits>
#  include <mach-o/dyld.h>
#elif defined(_WIN32)
#  include <windows.h>
#else
#  include <climits>
#  include <unistd.h>
#endif

//------------------------------------------------------------------------------
//! \brief Name of the environment variable holding extra search directories.
static constexpr char const* ENV_DATA_PATH = "OPENGLASSBOX_DATA_PATH";

//------------------------------------------------------------------------------
std::string DataPath::executableDirectory()
{
    std::string path;

#if defined(__APPLE__)
    char buffer[PATH_MAX + 1];
    uint32_t size = sizeof(buffer);
    if (_NSGetExecutablePath(buffer, &size) == 0)
    {
        path = buffer;
    }
#elif defined(_WIN32)
    char buffer[MAX_PATH];
    DWORD const length = GetModuleFileNameA(nullptr, buffer, sizeof(buffer));
    if ((length > 0u) && (length < sizeof(buffer)))
    {
        path.assign(buffer, length);
    }
#else
    char buffer[PATH_MAX + 1];
    ssize_t const length = ::readlink("/proc/self/exe", buffer, sizeof(buffer) - 1u);
    if (length > 0)
    {
        path.assign(buffer, size_t(length));
    }
#endif

    if (path.empty())
        return path;

    size_t const separator = path.find_last_of("/\\");
    if (separator == std::string::npos)
        return {};

    return path.substr(0u, separator + 1u);
}

//------------------------------------------------------------------------------
DataPath DataPath::makeDefault(std::string const& commandLinePath)
{
    DataPath path;

    // Lowest priority: the directories known at build time.
    path.add(project::info::paths::data);

    // The data folder shipped next to the executable. Two layouts are covered:
    // an installed build, where data sits beside the binary, and a run from the
    // build directory of the source tree.
    std::string const exeDir = executableDirectory();
    if (!exeDir.empty())
    {
#if defined(__APPLE__)
        // Inside a macOS bundle the executable lives in Contents/MacOS.
        path.add(exeDir + "../Resources/");
#endif
        path.add(exeDir + "data/");
        path.add(exeDir + "../demo/data/");
        path.add(exeDir);
    }

    // The current working directory, so that running from the source tree works.
    path.add("demo/data/");
    path.add("data/");
    path.add(".");

    // Higher priority: the environment variable.
    char const* const env = ::getenv(ENV_DATA_PATH);
    if ((env != nullptr) && (env[0] != '\0'))
    {
        path.prepend(env);
    }

    // Highest priority: the command line.
    if (!commandLinePath.empty())
    {
        path.prepend(commandLinePath);
    }

    return path;
}

//------------------------------------------------------------------------------
DataPath::DataPath(std::string const& path, char const delimiter)
  : m_delimiter(delimiter)
{
    add(path);
}

//------------------------------------------------------------------------------
void DataPath::add(std::string const& path)
{
    if (!path.empty())
    {
        split(path, false);
    }
}

//------------------------------------------------------------------------------
void DataPath::prepend(std::string const& path)
{
    if (!path.empty())
    {
        split(path, true);
    }
}

//------------------------------------------------------------------------------
void DataPath::reset(std::string const& path)
{
    m_search_paths.clear();
    split(path, false);
}

//------------------------------------------------------------------------------
void DataPath::clear()
{
    m_search_paths.clear();
}

//------------------------------------------------------------------------------
void DataPath::remove(std::string const& path)
{
    m_search_paths.remove(path);
}

//------------------------------------------------------------------------------
bool DataPath::exist(std::string const& path) const
{
    struct stat buffer;
    return stat(path.c_str(), &buffer) == 0;
}

//------------------------------------------------------------------------------
std::pair<std::string, bool> DataPath::find(std::string const& filename) const
{
    if (DataPath::exist(filename))
        return std::make_pair(filename, true);

    for (auto const& it: m_search_paths)
    {
        std::string file(it + filename);
        if (DataPath::exist(file))
            return std::make_pair(file, true);
    }

    // Not found
    return std::make_pair(std::string(), false);
}

//------------------------------------------------------------------------------
std::string DataPath::expand(std::string const& filename) const
{
    for (auto const& it: m_search_paths)
    {
        std::string file(it + filename);
        if (DataPath::exist(file))
            return file;
    }

    return filename;
}

//------------------------------------------------------------------------------
bool DataPath::open(std::string& filename, std::ifstream& ifs, std::ios_base::openmode mode) const
{
    ifs.open(filename.c_str(), mode);
    if (ifs)
        return true;

    for (auto const& it: m_search_paths)
    {
        std::string file(it + filename);
        ifs.open(file.c_str(), mode);
        if (ifs)
        {
            filename = file;
            return true;
        }
    }

    // Not found
    return false;
}

//------------------------------------------------------------------------------
bool DataPath::open(std::string& filename, std::ofstream& ofs, std::ios_base::openmode mode) const
{
    ofs.open(filename.c_str(), mode);
    if (ofs)
        return true;

    for (auto const& it: m_search_paths)
    {
        std::string file(it + filename);
        ofs.open(file.c_str(), mode);
        if (ofs)
        {
            filename = file;
            return true;
        }
    }

    // Not found
    return false;
}

//------------------------------------------------------------------------------
bool DataPath::open(std::string& filename, std::fstream& fs, std::ios_base::openmode mode) const
{
    fs.open(filename.c_str(), mode);
    if (fs)
        return true;

    for (auto const& it: m_search_paths)
    {
        std::string file(it + filename);
        fs.open(file.c_str(), mode);
        if (fs)
        {
            filename = file;
            return true;
        }
    }

    // Not found
    return false;
}

//------------------------------------------------------------------------------
std::vector<std::string> DataPath::pathes() const
{
    std::vector<std::string> res;
    res.reserve(m_search_paths.size());
    for (auto const& it: m_search_paths)
    {
        res.push_back(it);
    }

    return res;
}

//------------------------------------------------------------------------------
std::string DataPath::toString() const
{
    std::string string_path;

    for (auto const& it: m_search_paths)
    {
        if (!string_path.empty())
        {
            string_path += m_delimiter;
        }
        string_path += it;
    }

    return string_path;
}

//------------------------------------------------------------------------------
void DataPath::split(std::string const& path, bool front)
{
    std::stringstream ss(path);
    std::string directory;
    // Splitting produces the directories in order; inserting them one by one at
    // the front would reverse them, hence the intermediate list.
    std::list<std::string> directories;

    while (std::getline(ss, directory, m_delimiter))
    {
        if (directory.empty())
            continue ;

        if ((*directory.rbegin() == '\\') || (*directory.rbegin() == '/'))
            directories.push_back(directory);
        else
            directories.push_back(directory + "/");
    }

    if (front)
    {
        m_search_paths.splice(m_search_paths.begin(), directories);
    }
    else
    {
        m_search_paths.splice(m_search_paths.end(), directories);
    }
}
