@startuml

class Simulation {
+update(dt)
}

class Box 

Simulation -> "*" Box
Box -> "*" Map
Box -> "*" Path
Box -> "*" Agent

Path --> "*" Way
Way --> "*" Node

Unit --> "*" Resource
Unit --> "*" Rule

Map -> Unit
Unit <- Node

@enduml
