name: Non regression tests for OpenGlassBox
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  non_regression_windows:
    name: Non regression tests on Windows
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-toolchain git mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja mingw-w64-x86_64-bc mingw-w64-x86_64-pkg-config mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_image
      - name: Download, configure and install Google test
        shell: msys2 {0}
        run: |
          wget https://github.com/google/googletest/archive/release-1.11.0.tar.gz
          tar xf release-1.11.0.tar.gz
          cd googletest-release-1.11.0
          cmake -G "MinGW Makefiles" -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON .
          mingw32-make install
      - name: Compile OpenGlassBox
        shell: msys2 {0}
        run: |
          make download-external-libs
          V=1 make compile-external-libs
          V=1 make -j$(nproc)
          make install
      - name: Do non regression tests
        shell: msys2 {0}
        run: |
          cd tests
          V=1 make -j$(nproc)
          ../build/OpenGlassBox-tests
      - name: Check if the library can be linked against a project
        shell: msys2 {0}
        run: |
          export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/C:/Program Files (x86)/googletest-distribution/lib/pkgconfig"
          git clone https://github.com/Lecrapouille/LinkAgainstMyLibs.git --recurse-submodules --depth=1
          cd LinkAgainstMyLibs/OpenGlassBox
          V=1 make -j$(nproc)
          ./build/OpenGlassBox

  non_regression_linux:
    name: Non regression tests on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install pkg-config libdw-dev lcov libsdl2-dev libsdl2-image-dev
      - name: Download, configure and install Google test
        run: |
          wget https://github.com/google/googletest/archive/release-1.11.0.tar.gz
          tar xf release-1.11.0.tar.gz
          cd googletest-release-1.11.0
          cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON .
          sudo make install
      - name: Compile OpenGlassBox
        run: |
          make download-external-libs
          V=1 make compile-external-libs
          V=1 make -j`nproc --all`
          sudo make install
      - name: Do non regression tests
        run: |
          cd tests
          V=1 make -j`nproc --all`
          ../build/OpenGlassBox-tests
      - name: Check if the library can be linked against a project
        run: |
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
          git clone https://github.com/Lecrapouille/LinkAgainstMyLibs.git --recurse-submodules --depth=1
          cd LinkAgainstMyLibs/OpenGlassBox
          V=1 make -j`nproc --all`
          ./build/OpenGlassBox

  non_regression_macos:
    name: Non regression tests on MacOS X
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install packages
        run: |
          brew install pkg-config lcov sdl2 sdl2_image
      - name: Download, configure and install Google test
        run: |
          wget https://github.com/google/googletest/archive/release-1.11.0.tar.gz
          tar xf release-1.11.0.tar.gz
          cd googletest-release-1.11.0
          cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON .
          sudo make install
      - name: Compile OpenGlassBox
        run: |
          make download-external-libs
          make compile-external-libs
          make -j`sysctl -n hw.logicalcpu`
#          sudo make install
      - name: Do non regression tests
        run: |
          cd tests
          make -j`sysctl -n hw.logicalcpu`
          ../build/OpenGlassBox-tests
#      - name: Check if the library can be linked against a project
#        run: |
#          git clone https://github.com/Lecrapouille/LinkAgainstMyLibs.git --recurse-submodules --depth=1
#          cd LinkAgainstMyLibs/OpenGlassBox
#          make -j`sysctl -n hw.logicalcpu`
#          ./build/OpenGlassBox